apiVersion: v1
kind: Service
metadata:
  name: m4l-telemetry-api
  namespace: telemetry
  labels:
    app.kubernetes.io/name: m4l-telemetry-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: m4l-telemetry-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
